@extends('index_Chuan.Layout.master')
@section('menu')
    @include('index_Chuan.Layout.menu')
@endsection
@section('content')
    @include('index_Chuan.Content_index.content')
@endsection
@section('slide')
    @include('index_Chuan.Layout.slide')
@endsection